rainforest_ajax/config/routes.rb
Rails.application.routes.draw do
  resources :products do
    resources :reviews, only: [:show, :create, :destroy]
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

rainforest_ajax/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews


  validates :description, :name, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars)
  end
end

rainforest_ajax/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

rainforest_ajax/app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews


  has_secure_password

  validates :name, presence: true
end

rainforest_ajax/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end
end

rainforest_ajax/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%")
    else
      Product.all.page(params[:page])
    end

    respond_to do |format|
      format.html do
        if request.xhr?
          render @products
        else
          render 'index'
        end
      end

      format.js { render 'index' }
    end

    # if making a script type AJAX call:
    # can be refactored to
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
  end

  def show
    @product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

rainforest_ajax/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :ensure_logged_in, only: [:create, :destroy]
  before_filter :load_product

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to product_path(@product.id), notice: 'Review added.' }
        format.js {}
      else
        format.html { render 'products/show', alert: 'There was an error.' }
        format.js {}
      end
    end
  end


  def destroy
    @review = Review.find(params[:id])
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

rainforest_ajax/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

rainforest_ajax/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to products_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

rainforest_ajax/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest_ajax/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest_ajax/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest_ajax/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest_ajax/app/helpers/users_helper.rb
module UsersHelper
end

rainforest_ajax/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header id="site-header">
      <h1>Rainforest</h1>
      <div class="page-entries">
        <%= page_entries_info @products if @products %>
      </div>
    </header>

    <main>
      <% if flash[:notice] %>
        <p id="notice"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p id="alert"><%= flash[:alert] %></p>
      <% end %>

      <p class="userinfo">
        <% if current_user %>
          Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
        <% else %>
          <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        <% end %>
      </p>

      <%= yield %>
    </main>
  </body>
</html>

rainforest_ajax/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rainforest_ajax/app/views/products/_product.html.erb
<%= link_to product_path(product.id) do %>
  <h2>
    <%= number_to_currency(product.formatted_price) %>
    <%= product.name %>
  </h2>
<% end %>
<!-- keeps the description to 100 characters or less -->
<p><%= truncate(product.description, length: 100) %></p>

rainforest_ajax/app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
  <div class="review">
    <div class="poster">
      Posted by <%= review.user.name %> on <%= review.created_at %>
    </div>
    <p class="comment">
      <%= review.comment %>
    </p>
  </div>
<% end %>

rainforest_ajax/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

rainforest_ajax/app/views/products/index.html.erb
<h1>Listing products</h1>
<p class="page-entries"><%= page_entries_info @products %></p>

<%= link_to 'New Product', new_product_path %>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<div id="products">
  <%= render @products %>
</div>

<%= paginate @products %>

rainforest_ajax/app/views/products/index.js.erb
<% if params[:search] %>
  $('#products').html('<%= j(render @products) %>');
<% else %>
  $('#products').append('<%= j(render @products) %>');
  $('.page-entries').html('<%= j(page_entries_info @products) %>');
  $('.pagination').replaceWith('<%= j(paginate @products) %>');
<% end %>

rainforest_ajax/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

rainforest_ajax/app/views/products/show.html.erb
<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price in cents:</b>
  <%= @product.formatted_price %>
</p>

<h3>Reviews</h3>
<div id="review-list">
  <%= render :partial => "reviews" %>
</div>


<% if current_user %>
  <h4>New Review</h4>

  <%= form_for([@product, @review], remote: true) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p>
<% end %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>



<script type="text/javascript">

  $(document).ready(function() {
     $("#new_review")
        .on('ajax:beforeSend', function() {alert("loading!");})
        .on('ajax:success', function(data, status, xhr) {alert("success!");})
        .on('ajax:error', function(xhr, status, error) {alert("error!");})
        .on('ajax:complete', function() {alert("complete!");});
  });

</script>

rainforest_ajax/app/views/products/show.js.erb
$('body').append("<%= escape_javascript(render @product%>");

rainforest_ajax/app/views/reviews/_review.html.erb
<p>
  <%= review.comment %>
  <br>
  <% if review.user != nil %>
    <em> by <%= review.user.email %></em>
    Added on: <%= review.created_at %>
  <% end %>
</p>

rainforest_ajax/app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

rainforest_ajax/app/views/reviews/create.js.erb
$('.reviews').append('<%= j(render @review) %>');
$('#review_comment').val('');

alert("I'm responding to your request!");

$("#review-list").html("<%= escape_javascript(render(:partial => 'products/reviews')) %>");

rainforest_ajax/app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

rainforest_ajax/app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

rainforest_ajax/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

rainforest_ajax/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>